name: Test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
env: LETS_SEE:

jobs:
  test1:
    name: test 1
    runs-on: ubuntu-20.04

    steps:
    - name: checkout codes
      uses: actions/checkout@v2

    - name: set env
      run: |
        echo "1: $LETS_SEE"
        LETS_SEE=$(( 1+1 ))
        echo "2: $LETS_SEE"

#        echo "LETS_SEE=yes" >> $GITHUB_ENV
#    - name: test environment variable
#      run: |
#        echo "== HELLO from GHA =="
#        echo $LETS_SEE
#        ./ms.sh
#        echo $LETS_SEE
#        #pip3 install PyGithub==1.54.1
#
#    - name: subsequent step
#      run: echo $LETS_SEE
